export const GET_CLASS_STUDENTS_REQUEST = 'app/Classroom/GET_CLASS_STUDENTS_REQUEST';
export const GET_CLASS_STUDENTS_SUCCESS = 'app/Classroom/GET_CLASS_STUDENTS_SUCCESS';
export const GET_CLASS_STUDENTS_ERROR = 'app/Classroom/GET_CLASS_STUDENTS_ERROR';
