export const GET_CLASS_STUDENTS_REQUEST = 'app/Classroom/GET_CLASS_STUDENTS_REQUEST';
export const GET_CLASS_STUDENTS_SUCCESS = 'app/Classroom/GET_CLASS_STUDENTS_SUCCESS';
export const GET_CLASS_STUDENTS_ERROR = 'app/Classroom/GET_CLASS_STUDENTS_ERROR';
export const DELETE_CLASS_STUDENT_REQUEST = 'app/Classroom/DELETE_CLASS_STUDENT_REQUEST';
export const DELETE_CLASS_STUDENT_SUCCESS = 'app/Classroom/DELETE_CLASS_STUDENT_SUCCESS';
export const DELETE_CLASS_STUDENT_ERROR = 'app/Classroom/DELETE_CLASS_STUDENT_ERROR';
export const EXPORT_STUDENTS_REQUEST = 'app/Classroom/EXPORT_STUDENTS_REQUEST';
