export const CREATE_COURSE_REQUEST = 'app/CoursesAdd/CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'app/CoursesAdd/CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_ERROR = 'app/CoursesAdd/CREATE_COURSE_ERROR';
