export const PUT_UPDATE_ACCOUNT_REQUEST = 'app/AccountEdit/PUT_UPDATE_ACCOUNT_REQUEST';
export const PUT_UPDATE_ACCOUNT_SUCCESS = 'app/AccountEdit/PUT_UPDATE_ACCOUNT_SUCCESS';
export const PUT_UPDATE_ACCOUNT_ERROR = 'app/AccountEdit/PUT_UPDATE_ACCOUNT_ERROR';
