export const CREATE_SCHOOL_REQUEST = 'app/SchoolsAdd/CREATE_SCHOOL_REQUEST';
export const CREATE_SCHOOL_SUCCESS = 'app/SchoolsAdd/CREATE_SCHOOL_SUCCESS';
export const CREATE_SCHOOL_ERROR = 'app/SchoolsAdd/CREATE_SCHOOL_ERROR';
