export const GET_NOT_STUDENTS_OF_CLASS_REQUEST = 'app/ClassUsersAdd/GET_NOT_STUDENTS_OF_CLASS_REQUEST';
export const GET_NOT_STUDENTS_OF_CLASS_SUCCESS = 'app/ClassUsersAdd/GET_NOT_STUDENTS_OF_CLASS_SUCCESS';
export const GET_NOT_STUDENTS_OF_CLASS_ERROR = 'app/ClassUsersAdd/GET_NOT_STUDENTS_OF_CLASS_ERROR';
export const SET_SELECTED_USERS = 'app/ClassUsersAdd/SET_SELECTED_USERS';

export const POST_ADD_USERS_TO_CLASS_REQUEST = 'app/ClassUsersAdd/POST_ADD_USERS_TO_CLASS_REQUEST';
export const POST_ADD_USERS_TO_CLASS_SUCCESS = 'app/ClassUsersAdd/POST_ADD_USERS_TO_CLASS_SUCCESS';
export const POST_ADD_USERS_TO_CLASS_ERROR = 'app/ClassUsersAdd/POST_ADD_USERS_TO_CLASS_ERROR';
