export const SIGN_IN_BY_EMAIL_REQUEST = 'app/Login/SIGN_IN_BY_EMAIL_REQUEST';
export const SIGN_IN_BY_EMAIL_SUCCESS = 'app/Login/SIGN_IN_BY_EMAIL_SUCCESS';
export const SIGN_IN_BY_EMAIL_ERROR = 'app/Login/SIGN_IN_BY_EMAIL_ERROR';
