export const GET_COURSES_REQUEST = 'app/ClassDuplicate/GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'app/ClassDuplicate/GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'app/ClassDuplicate/GET_COURSES_ERROR';
export const POST_DUPLICATE_CLASS_REQUEST = 'app/ClassDuplicate/POST_DUPLICATE_CLASS_REQUEST';
export const POST_DUPLICATE_CLASS_SUCCESS = 'app/ClassDuplicate/POST_DUPLICATE_CLASS_SUCCESS';
export const POST_DUPLICATE_CLASS_ERROR = 'app/ClassDuplicate/POST_DUPLICATE_CLASS_ERROR';
